const DELETION_TYPES = {
  SELF_DELETE: 'SELF_DELETE',
  ADMIN_DELETE: 'ADMIN_DELETE',
}

const DELETION_CONFIG = {
  REQUIRE_PASSWORD_CONFIRMATION: false,
  USE_SOFT_DELETE: true,
}

module.exports = {
  DELETION_TYPES,
  DELETION_CONFIG,
}